[package]
name = "kkmypk-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6"
actix-web = "4"
actix-web-actors = "4"
actix = "0.13"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "time"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio-stream = "0.1"
uuid = { version = "1", features = ["v4", "serde"] }
