[package]
name = "jxwxmk"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13"
actix-web = "4"
actix-web-actors = "4"
chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.11"
log = "0.4"
mime_guess = "2"
rand = "0.8"
rust-embed = "8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "uuid", "json", "chrono"] }
tokio = { version = "1", features = ["rt", "macros", "time"] }
uuid = { version = "1", features = ["v4", "serde"] }

[dev-dependencies]
actix-test = "0.1"
awc = "3"
futures-util = "0.3"
