[package]
name = "jxwxmk_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13"
actix-web = "4"
actix-web-actors = "4"
actix-files = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["serde", "v4"] }
log = "0.4"
env_logger = "0.10"
rust-embed = "8.0"
mime_guess = "2.0"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "uuid", "time", "json"] }
dotenvy = "0.15"

[dev-dependencies]
actix-test = "0.1"
awc = "3"
tempfile = "3"

[[bin]]
name = "server"
path = "main.rs"
