[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
net = { path = "../../crates/net" }
game = { path = "../../crates/game" }
assets = { path = "../../crates/assets" }
persistence = { path = "../../crates/persistence" }
config = { path = "../../crates/config" }
env_logger = "0.10"
log = "0.4"
tokio = { version = "1", features = ["full"] }
home = "=0.5.9"
time = "=0.3.36"
base64ct = "=1.6.0"
actix-web = "4"
actix = "0.13"
