[package]
name = "starve-game"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "starve-game"
path = "src/server/main.rs"

[dependencies]
actix-web = "4"
actix-ws = "0.3"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
bincode = "1.3"
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
thiserror = "1"
md5 = "0.7"