[package]
name = "assets"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
actix-web = { workspace = true }

[dev-dependencies]
actix-rt = "2.9"
