[package]
name = "world"
version.workspace = true
edition.workspace = true

[dependencies]
config = { workspace = true }
protocol = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
rand = { workspace = true }
