[package]
name = "world"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.0", features = ["serde", "v4"] }
config = { path = "../config" }
serde_json = "1.0"
rand = "0.8"
rand_chacha = "0.3"
