[package]
name = "world"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
protocol = { path = "../protocol" }
config = { path = "../config" }
uuid = { version = "1.0", features = ["serde", "v4"] }
