version: "3.8"

services:
  jxwxmk:
    image: jxwxmk:latest
    ports:
      - "8080:8080"
    volumes:
      - jxwxmk_pgdata:/var/lib/postgresql/data
      - ../../../config:/app/config
    restart: unless-stopped

volumes:
  jxwxmk_pgdata:
