version: "3.8"

services:
  jxwxmk:
    build:
      context: ../../..
      dockerfile: src/runtime/Dockerfile
    image: jxwxmk:local
    user: "root"
    ports:
      - "8080:8080"
    volumes:
      - jxwxmk_pgdata:/var/lib/postgresql/data
      - ../../../config:/app/config
    restart: unless-stopped

volumes:
  jxwxmk_pgdata: