version: '3.8'
services:
  server:
    build:
      context: ../../../
      dockerfile: src/runtime/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../../../config:/app/config
    environment:
      - RUST_LOG=debug
